//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDKPOCDMPTest.WS1.WS2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculatedDataset", Namespace="http://schemas.datacontract.org/2004/07/GeoDKPOCDMPTest.WS2")]
    [System.SerializableAttribute()]
    public partial class CalculatedDataset : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefId {
            get {
                return this.RefIdField;
            }
            set {
                if ((this.RefIdField.Equals(value) != true)) {
                    this.RefIdField = value;
                    this.RaisePropertyChanged("RefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValueA {
            get {
                return this.ValueAField;
            }
            set {
                if ((this.ValueAField.Equals(value) != true)) {
                    this.ValueAField = value;
                    this.RaisePropertyChanged("ValueA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValueB {
            get {
                return this.ValueBField;
            }
            set {
                if ((this.ValueBField.Equals(value) != true)) {
                    this.ValueBField = value;
                    this.RaisePropertyChanged("ValueB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValueC {
            get {
                return this.ValueCField;
            }
            set {
                if ((this.ValueCField.Equals(value) != true)) {
                    this.ValueCField = value;
                    this.RaisePropertyChanged("ValueC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetCalculatedDataSet", ReplyAction="http://tempuri.org/IService2/GetCalculatedDataSetResponse")]
        GeoDKPOCDMPTest.WS1.WS2.CalculatedDataset GetCalculatedDataSet(int id, System.Nullable<int> ValueA, System.Nullable<int> ValueB, System.Nullable<int> ValueC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetCalculatedDataSet", ReplyAction="http://tempuri.org/IService2/GetCalculatedDataSetResponse")]
        System.Threading.Tasks.Task<GeoDKPOCDMPTest.WS1.WS2.CalculatedDataset> GetCalculatedDataSetAsync(int id, System.Nullable<int> ValueA, System.Nullable<int> ValueB, System.Nullable<int> ValueC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : GeoDKPOCDMPTest.WS1.WS2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<GeoDKPOCDMPTest.WS1.WS2.IService2>, GeoDKPOCDMPTest.WS1.WS2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GeoDKPOCDMPTest.WS1.WS2.CalculatedDataset GetCalculatedDataSet(int id, System.Nullable<int> ValueA, System.Nullable<int> ValueB, System.Nullable<int> ValueC) {
            return base.Channel.GetCalculatedDataSet(id, ValueA, ValueB, ValueC);
        }
        
        public System.Threading.Tasks.Task<GeoDKPOCDMPTest.WS1.WS2.CalculatedDataset> GetCalculatedDataSetAsync(int id, System.Nullable<int> ValueA, System.Nullable<int> ValueB, System.Nullable<int> ValueC) {
            return base.Channel.GetCalculatedDataSetAsync(id, ValueA, ValueB, ValueC);
        }
    }
}
