//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDKPOCDMPTest.WS2.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PythagorasValue
    {
        public int Id { get; set; }
        public int DB1Id { get; set; }
        public Nullable<double> A_Value { get; set; }
        public Nullable<double> B_Value { get; set; }
        public Nullable<double> C_Value { get; set; }
    }
}
