//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDKPOCDMPTest.WS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public string ErrorMessage { get; set; }
    }
}
