//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoDKPOCDMPTest.WS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PythagorasValue
    {
        public int Id { get; set; }
        public int DB1iD { get; set; }
        public Nullable<double> ValueA { get; set; }
        public Nullable<double> ValueB { get; set; }
        public Nullable<double> ValueC { get; set; }
    }
}
